M = {}

M.local_quotes = {
  "I'm a teapot. 🫖\n      - HTTP 418",
  "Asparagus comes in three colors: green, white and purple",
  "The first known contraceptive was crocodile dung, used by\nEgyptians in 2000 B.C",
  "Approximately 71% of American chocolate eaters prefer to eat\nmilk chocolate",
  "Arabic numerals were not invented by Arabs, but were\ninvented in India by the Hindus",
  "The Tonle Sap River in Cambodia flows north for almost half\nthe year and then south for the rest of the year",
  "In twins, there is a great chance that one will be left\nhanded",
  "Some people drink the urine of pregnant women to build up\ntheir immune system",
  "Rocky Mountain spotted fever is a disease caused by ticks",
  "The Toronto Maple Leafs used to be called the Toronto\nArenas, then the St. Patricks and finally the Maple Leafs",
  "In the United States birds and planes collided more than\n22,000 times between the years of 1990 and 1998",
  "The oldest actor to win a Best Actor Oscar is Henry Fonda.\nHe was 76 when he won it",
  "A headache and inflammatory pain can be reduced by eating 20\ntart cherries",
  "People with darker skin will not wrinkle as fast as people\nwith lighter skin",
  "Turkeys have a wingspan of approximately 4.5 feet",
  "The sport of surfing originated in Hawaii",
  "An adult porcupine has approximately 30,000 quills on its\nbody, which are replaced every year",
  'The first toilet ever seen on television was on "Leave It To',
  'Beaver".',
  "Milk chocolate was invented in Switzerland by David Peter in\n1876",
  "Chocolate can be fatal to dogs. Chocolate contains a\nchemical theobromine, which is poisonous to dogs",
  "The only king without a moustache in a deck of cards is the\nking of hearts",
  "The sun is approximately 149 million kilometres from the\nearth",
  "Hair will fall out faster on a person that is on a crash\ndiet",
  "Contrary to popular beliefs, chocolate does not cause acne",
  "The average person spends two weeks of their life kissing",
  "There are three golf balls sitting on the moon",
  'Shakespeare invented the word "assassination" and "bump."',
  "On average, an American relocates 11 times in their life",
  "The largest spider ever was the Megarachne which had a\ndiameter of 50 cm. The fossil was found in Argentina",
  'The word Karate means, "empty hand."',
  "The biggest bug in the world is the Goliath Beetle which can\nweigh up to 3.5 ounces and be 4.5 inches long",
  "During the holiday season, approximately $220 million worth\nof Poinsettias are sold",
  "The decomposition point of Olive Oil is 220 degrees Celsius",
  "In the United States, you are more likely to be killed by a\nbee string than a shark attack",
  "Crabs have very small hairs on their claws and other parts\nof their body to help detect water currents and vibrations",
  "More people are killed by donkeys annually than are killed\nin plane crashes",
  "Each day Americans 15 and over spend an average of 55\nminutes of driving",
  "Coca-Cola was originally green",
  "For every human in the world there are one million ants",
  "The sport of surfing originated in Hawaii",
  "The Olympics were originally held for the Greek god Zeus",
  "Ukrainian monk, Dionysius Exiguus, created the modern day\nChristian calendar",
  "Every year, 50,000,000 automobiles are produced in the\nworld.",
  "On average, an American relocates 11 times in their life",
  "The smallest bone in the human body is the stirrup bone,\nwhich is located in the ear",
  "Over 90% of diseases are caused or complicated by stress",
  "Since the United Nations was founded in 1945, there have\nbeen 140 wars",
  "The most diners per capita in the world are located in the\nU.S. state New Jersey",
  "The two top toys in 1950 were Silly Putty which sold for $1,\nand Crayola crayons which sold for 50 cents",
  "Vatican City is the smallest country in the world, with a\npopulation of 1000 and a size 108.7 acres",
  "Sharks can sense a drop of blood from a mile away",
  "The Koala bear is not really a bear, but is really related\nto the kangaroo and the wombat.",
  "Wild Flamingos are pink because they consume vast quantities\nof algae and brine shrimp",
  "From all the states, Montana has the most different species\nof animals",
  "The small intestine in the human body is about 2 inches\naround, and 22 feet long",
  "Diamonds were first discovered in the riverbeds of the\nGolconda region of India over 4,000 years ago.",
  "The only species of turtle that lives in the open ocean is\nthe sea turtle",
  "Approximately 20% of Americans have a passport",
  "Every day, the Hubble telescope transmits enough data to fit\n10,000 standard computer disks",
  "There are approximately 45 billion fat cells in an average\nadult",
  "The human face is made up of 14 bones",
  "Egyptian pyramid builders used to eat a lot of garlic\nbecause they thought it would increase their strength",
  "A superstition in baseball is to never lend your bat to\nanyone or you will be jinxed",
  "There is a species of bird, Antpitta avis canis Ridgley,\nthat barks like a dog",
  "The Olympic Flame was introduced in 1928 in Amsterdam",
  "The temperature of lightning bolts is sometimes hotter than\nthe surface of the sun.",
  "570 gallons of paint would be needed to paint the outside of\nthe White House",
  "At the White House, president John Adams was said to be the\nfirst to display fireworks there",
  "Close to 80% of people who watch the Super Bowl on\ntelevision, only do so to view the commercials",
  "A dog by the name of Laika was launched into space aboard\nthe Russian spacecraft Sputnik 2 in 1957",
  "Bats emit ultrasonic sounds to communicate with each other",
  "Traveling by air is the safest means of transportation.",
  "Women smile more than men do",
  "There is a place called Hell, Michigan. It is about 50 miles\nfrom Detroit, Michigan",
  "Great Britain was the first country to issue postage stamps\nin 1840",
  "66% of wedding cards are hand delivered by people",
  "On average men spend 51 minutes a day grooming themselves",
  "The capital of Burkina Faso is Ouagadougou",
  "The colour blue has a calming effect. It causes the brain to\nrelease calming hormones",
  "According to Scientists, vampire bat saliva is the best\nknown medicine for keeping blood from clotting.",
  "Minimum wage was 0.25 per hour when it was first enacted in\n1938",
  "Early Romans used to use porcupine quills as toothpicks",
  "A house cat spends 70% of its time sleeping",
  "Americans on the average eat 18 acres of pizza every day",
  "A person who smokes a pack of cigarettes a day will on\naverage lose two teeth every ten years",
  "Benjamin Franklin invented the rocking chair.",
  "The average ice berg weighs 20,000,000 tons",
  "The Sears Tower located in Chicago, Illinois is made up\n76,000 tons of steel",
  "In 2001, the five most valuable brand names in order were\nCoca-Cola, Microsoft, IBM, GE, and Nokia",
  "The largest apple pie ever baked was forty by twenty three\nfeet",
  "Approximately 75% of human poop is made of water",
  "Approximately 87% of dog owners say that when they watch\nT.V. their dog curls up beside them or at their feet",
  "On average, 749 pounds of paper products is used by an\nAmerican individual annually",
  "Annually 7 million tons of textiles and clothing is thrown\nout. Out of this, only 12% is used again or recycled",
  "Keeping Warm With an Axe, is the title of a real how-to\nbook. Click Here For More Details",
  '"Go." is the shortest complete sentence in the English',
  "language",
  "The two top toys in 1950 were Silly Putty which sold for $1,\nand Crayola crayons which sold for 50 cents",
  "In a five card poker game there are 2,598,960 possible hands",
  "The longest game of Monopoly played underwater is 45 days",
  "Every U.S. bill regardless of denomination costs just 4\ncents to make",
  "Butterflies taste with their feet",
  "A snail can sleep for 3 years",
  "In most advertisements, including newspapers, the time\ndisplayed on a watch is 10:10",
  "Printed on the tablet being held by the Statue of Liberty is\nJuly IV, MDCCLXXVI",
  "Venus is the only planet that rotates clockwise",
  "Pikeville, Kentucky consumes the most Pepsi per capita then\nany other American city",
  "Eating parsley after eating an onion can help in getting rid\nof onion breath",
  "Movies approximately make five times more from video sales\nthan ticket sales",
  "In the U.S., the milk production per dairy cow is\napproximately 12,000 pounds",
  "Annually, an Australian eats 15 kg of bananas, which comes\nout to 27 meters of bananas",
  "In 2002, the most popular boat name in the U.S. was Liberty",
  "All babies are colour blind when they are born",
  "Eating a banana at night can help in falling asleep",
  "St. Patrick explained the Holy Trinity to King Laoghaire,\nusing the shamrock to illustrate the trinity",
  "Each day Americans 15 and over spend an average of 55\nminutes of driving",
  'DC-10, the name of an airplane stands for "Douglas\nCommercial."',
  "The average American drinks 400 glasses of milk in a year",
  "In Alabama, it is against the law to wear a fake mustache\nthat could cause laughter in the church",
  'The "Star Spangled Banner" did not become a national anthem',
  "until 1931. It was designated by an Act of Congress",
  "The Spring peeper (a frog) can survive the winter season\nwith 65% of its body water as ice",
  "Kissing can aid in reducing tooth decay. This is because the\nextra saliva helps in keeping the mouth clean",
  "The Nobel prize was first awarded in 1901",
  "The largest apple pie ever baked was forty by twenty three\nfeet",
  "The size of a red blood cell is 708 microns. This is\nequivalent to one millionth of a meter",
  "A newborn kangaroo weighs approximately 0.03 ounces and is\nsmall enough to fit in a teaspoon",
  "The human body has approximately 37,000 miles of capillaries",
  "On average 1,668 gallons of water are used by each person in\nthe United States daily",
  "Bamboo plants can grow up to 36 inches in a day.",
  "In 2002, dogs have killed more people in the U.S. than the\nGreat White shark has killed in the past 100 years",
  "Iguanas can stay under water for up to thirty minutes",
  "The ostrich has two toes on each feet which gives it greater\nspeed",
  "Every hour one billion cells in the body must be replaced",
  "Early sewing machines were destroyed by mobs or workers who\nfelt their jobs were threatened by automation",
  "Ramses II, a pharaoh of Egypt died in 1225 B.C. At the time\nof his death, he had fathered 96 sons and 60 daughters",
  "Hannibal, who was a soldier, had only one eye after getting\na disease while attacking Rome",
  "Soil that is heated by geysers are now making it possible to\nproduce bananas in Iceland",
  "A maple tree is usually tapped when the tree is at least 45\nyears old and has a diameter of 12 inches",
  "Every day, over five billion gallons of water are flushed\ndown toilets in the United States",
  "An alligator has about 80 teeth in its mouth at one time. An\nalligator can go through 3,000 teeth in a lifetime",
  "Average life span of a major league baseball: 7 pitches",
  'The "Star Spangled Banner" did not become a national anthem',
  "until 1931. It was designated by an Act of Congress",
  'Harley Proctor got the idea to name the soap "Ivory" while',
  "he was listening to a bible reading at a church in 1879",
  "In 2002, the most popular boat name in the U.S. was Liberty",
  "Bananas contain a natural chemical which can make a person\nhappy. This same chemical is found in Prozac",
  "There are coffee flavored PEZ",
  "Ancient Romans at one time used human urine as an ingredient\nin their toothpaste",
  "Finland has 187,888 lakes and 179,584 islands",
  "In 1946 Danon Yogurt were the first to add fruit to\ncommercially produced yogurt in U.S",
  "According to studies, men prefer to have white bedrooms and\nwomen prefer to have blue bedrooms",
  "In a year, the average Americans eats approximately 18\npounds of Turkey",
  "Close to 73% of girls in Bangladesh are married by age 18",
  "The sun is approximately 75% hydrogen, 25% helium by mass",
  "Hershey's Kisses are called that because the machine that\nmakes themlooks like it's kissing the conveyor belt.",
  "Some dolphins can swim up to 40 kilometers an hour",
  "The largest number of children born to one woman, who was a\nRussian peasant is 69",
  "The General Lee cars used in the popular show The Dukes of\nHazards were 1969 Dodge Chargers",
  "People of Salt Lake City eat the most lime-flavoured gelatin\nJell-O in the United States",
  "It took eleven years to built the Taj Mahal, (1632-1643)",
  "Most American women have their first baby when they are 24.3\nyears old",
  "Movies approximately make five times more from video sales\nthan ticket sales",
  "The largest LEGO castle that was ever built was built with\n400,000 LEGO bricks and was 4.45 m x 5.22 m",
  "Women are four times more likely to have foot problems than\nmen",
  "Lemons contain more sugar than strawberries",
  "Birds do not sweat, as they do not have sweat glands",
  "A study revealed that men that were born with a low birth\nweight were less likely to get married",
  "Cheetahs are the fastest land animal and can reach speeds up\nto 72mph",
  "Humans are the only primates that don't have pigment in the\npalms oftheir hands.",
  "On average, Guinness sells 7 million glasses of beer a day",
  "People in low-income homes spend 50% more time playing video\ngames than people in high-income homes",
  "Little Miss Muffet was a girl from the 16th century whose\nname was really Patience",
  "The only popcorn museum in the world is lcoated in Marion,\nOhio, USA",
  "Franklin Pierce was the first U.S. President to have a\nChristmas tree in the White House",
  'Canada is an Indian word meaning "village" or "settlement."',
  "Wasps that feed on ferment occasionally get drunk and pass\nout",
  "A maple tree is usually tapped when the tree is at least 45\nyears old and has a diameter of 12 inches",
  "Buttermilk does not contain any butter, but is a cultured\nmilk product which is usually made from fat free milk",
  "The greatest mountain range is the Mid-Ocean Ridge,\nextending 64,374 km from the Arctic Ocean to the Atlantic\nOcean",
  "Children laugh about 400 times a day, while adults laugh on\naverage only 15 times a day",
  "Hydrogen is the most common atom in the universe",
}

---Returns a random quote
---@return string
M.get_quote = function()
  return M.local_quotes[math.random(#M.local_quotes)]
end

return M
